In [1]:
# following an older tutorial
# https://scikit-learn.org/0.21/tutorial/basic/tutorial.html

In [2]:
from sklearn import datasets

https://scikit-learn.org/1.5/auto_examples/datasets/plot_iris_dataset.html  
"This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray

The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.

In [3]:
iris = datasets.load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Target names are names of the classes

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
# should give the ground truth, that corresponding to each 

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# Remember because I think we have to convert labels into numberical equivlaents

with some AI notes

# 
`iris.target`  tells you what each numeric label corresponds to.

`iris.target`
This gives the numeric labels (0, 1, 2) for each sample in the dataset, representing which species it belongs to.

Here:

0 → 'setosa'

1 → 'versicolor'

2 → 'virginica'

So in short:

iris.target_names is the mapping of class indices to names.

iris.target is the array of labels (integers) for each sample.

There are many reasons why we convert text labels like Setosa into numeric lables

In [9]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

iris.target_names

This is just the list of unique class labels in the dataset.

For the iris dataset, there are 3 species of iris flowers:

iris.target

This is the class label for each sample (row) in the dataset.

The iris dataset has 150 samples (rows).

So iris.target is an array of length 150, where each value is one of 0, 1, or 2.

how were we suppoed to know that 0 correspondes to setosa and so on?  
The connection between the numbers in iris.target and the species names is defined by the index order of iris.target_names.

How It Works

iris.target_names is:

['setosa', 'versicolor', 'virginica']


By convention, scikit-learn assigns:

0 → first element → 'setosa'

1 → second element → 'versicolor'

2 → third element → 'virginica'

So the index of the string in target_names is the label number used in target.

In [11]:
# iris.data

# iris.data

This is the feature matrix (the inputs, or X).

Shape: (150, 4) → 150 rows (samples), 4 columns (features).

Each row = one flower.

Each column = a measurement of that flower.

The 4 features are:

sepal length (cm)

sepal width (cm)

petal length (cm)

petal width (cm)

In [12]:
len(iris.data)

150

In [13]:
# iris.data

iris.data = numerical measurements of flowers (features).

iris.target = species labels (which species each row belongs to).

iris.target_names = the mapping from numbers to species names.

In [14]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In scikit-learn’s Iris dataset, the feature names are stored in the attribute:  
iris.feature_names

iris.target_names gives the human-readable mapping (['setosa', 'versicolor', 'virginica']).

iris.target gives the machine-readable numeric version ([0, 0, 1, 2, …]).

Internally, the ML model only sees numbers.

When presenting results to humans, we map back from the number to the name.

In [15]:
digits = datasets.load_digits()

In [16]:
# digits

In [17]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [18]:
digits.target

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [19]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Using an estimator for digits

"In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T)."

In [20]:
from sklearn import svm

In [21]:
clf = svm.SVC(gamma=0.001, C=100.)

In this example, we set the value of gamma manually. To find good values for these parameters, we can use tools such as grid search and cross validation.

In [22]:
clf

SVC(C=100.0, gamma=0.001)

In [23]:
type(clf)

sklearn.svm._classes.SVC

In [24]:
# clf.fit
# clf.predict

clf (for classifier

The clf (for classifier) estimator instance is first fitted to the model; that is, it must learn from the model. This is done by passing our training set to the fit method. For the training set, we’ll use all the images from our dataset, except for the last image, which we’ll reserve for our predicting. We select the training set with the [:-1] Python syntax, which produces a new array that contains all but the last item from digits.data:

In [25]:
# train the classifier with all the data except last one for X and y

In [26]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, gamma=0.001)

Now you can predict new values. In this case, you’ll predict using the last image from digits.data. By predicting, you’ll determine the image from the training set that best matches the last image.

In [27]:
# predict what digit it should be based on the trained classifier

In [28]:
clf.predict(digits.data[-1:])

array([8])

In [29]:
digits = datasets.load_digits()

In [30]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64)),
 'target': array([0, 1, 2, ..., 8, 9, 8], shape=(1797,)),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7'

In [31]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [32]:
digits.target

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

# Model persistence

It is possible to save a model in scikit-learn by using Python’s built-in persistence model, pickle

In [33]:
from sklearn import svm

In [34]:
from sklearn import datasets

In [35]:
# i am not so such what gamma parameter means. I forgot.
clf = svm.SVC(gamma='scale')

In [36]:
iris = datasets.load_iris()

In [37]:
# give data and target X and y values which make it easier for me to remember
X, y = iris.data, iris.target

In [38]:
# fit it on X and y
clf.fit(X, y) 

SVC()

In [39]:
import pickle

In [40]:
# save the model to a file
s = pickle.dumps(clf)

In [41]:
clf2 = pickle.loads(s)

In [42]:
# predict the flower for first value of X
clf2.predict(X[0:1])

array([0])

In [43]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Type casting

In [1]:
import numpy as np

In [2]:
from sklearn import random_projection

In [3]:
rng = np.random.RandomState(0)

In [4]:
rng

RandomState(MT19937) at 0x78AE13D69340

In [5]:
# generating random numbers in numpy in with 10 rows and 2000 items per row
X = rng.rand(10, 2000)

In [6]:
X

array([[0.5488135 , 0.71518937, 0.60276338, ..., 0.48010781, 0.64386404,
        0.50177313],
       [0.81151847, 0.47608399, 0.52315599, ..., 0.83000295, 0.93280618,
        0.30833843],
       [0.29264205, 0.56651827, 0.13741443, ..., 0.69652287, 0.48369661,
        0.33955073],
       ...,
       [0.32059506, 0.24986687, 0.03107279, ..., 0.38938909, 0.93272   ,
        0.33276632],
       [0.39553738, 0.84401749, 0.15044175, ..., 0.53561083, 0.35458205,
        0.93578099],
       [0.8140271 , 0.85133715, 0.43113659, ..., 0.44645576, 0.36012661,
        0.62588665]], shape=(10, 2000))

In [7]:
# type casting?
X = np.array(X, dtype='float32')

In [8]:
X

array([[0.5488135 , 0.71518934, 0.60276335, ..., 0.4801078 , 0.64386404,
        0.5017731 ],
       [0.8115185 , 0.476084  , 0.523156  , ..., 0.83000296, 0.9328062 ,
        0.30833843],
       [0.29264206, 0.56651825, 0.13741443, ..., 0.6965229 , 0.4836966 ,
        0.33955073],
       ...,
       [0.32059506, 0.24986687, 0.03107279, ..., 0.3893891 , 0.93272   ,
        0.33276632],
       [0.39553738, 0.8440175 , 0.15044175, ..., 0.53561085, 0.35458204,
        0.935781  ],
       [0.81402713, 0.85133713, 0.43113658, ..., 0.44645575, 0.3601266 ,
        0.6258866 ]], shape=(10, 2000), dtype=float32)

In [9]:
transformer = random_projection.GaussianRandomProjection()

In [10]:
transformer

GaussianRandomProjection()

In [11]:
X_new = transformer.fit_transform(X)

In [14]:
help(transformer.fit_transform)

Help on method fit_transform in module sklearn.base:

fit_transform(X, y=None, **fit_params) method of sklearn.random_projection.GaussianRandomProjection instance
    Fit to data, then transform it.
    
    Fits transformer to `X` and `y` with optional parameters `fit_params`
    and returns a transformed version of `X`.
    
    Parameters
    ----------
    X : array-like of shape (n_samples, n_features)
        Input samples.
    
    y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
        Target values (None for unsupervised transformations).
    
    **fit_params : dict
        Additional fit parameters.
    
    Returns
    -------
    X_new : ndarray array of shape (n_samples, n_features_new)
        Transformed array.



In [12]:
X_new

array([[ 1.0471812 ,  0.02367403,  0.00643635, ..., -0.96064484,
        -0.8774427 ,  0.19891047],
       [ 0.95350516, -0.55844146, -0.29920268, ..., -1.2128937 ,
        -0.45771876,  0.021502  ],
       [ 0.7914285 , -0.5321381 , -0.24539874, ..., -0.3610025 ,
        -1.4254637 ,  0.32652515],
       ...,
       [ 1.0529857 , -0.9759328 , -0.15339635, ..., -0.71688044,
        -0.44989917,  0.03582075],
       [ 0.46766806, -0.2641603 , -0.37652582, ..., -0.7866382 ,
        -1.1171193 ,  0.66561913],
       [ 0.75835943, -0.6121828 , -0.17376736, ..., -1.2291455 ,
        -0.5190437 ,  0.04292862]], shape=(10, 1973), dtype=float32)

In [13]:
X_new.dtype

dtype('float32')

In [44]:
# classifier.score(X_test, y_test):
# below will give an error. it needs a 2D array
# clf.score(X[0], y[0])

In [45]:
# keep 2D/1D shapes via slicing
# note that X[0} and y[0
clf.score(X[0:1], y[0:1])          # -> 1.0 if correct, 0.0 if not

1.0

In [46]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [47]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [48]:
X[0:1] == X[0]

array([[ True,  True,  True,  True]])

In [49]:
X[0:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [50]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [51]:
X[0].shape

(4,)

In [52]:
X[0:1].shape

(1, 4)

Note that X[0] and X[0:1] have different sahpes and so are not exactly the same

X[0:1]

Shape: (1, 4) → a 2D array with 1 row and 4 columns.

You’re slicing out the first row, but keeping the “row dimension”.

X[0]

Shape: (4,) → a 1D array with 4 numbers.

You’re pulling out the first row and collapsing it into a flat vector.

In [54]:
# Try dumping to a file
# https://www.digitalocean.com/community/tutorials/python-pickle-example
# Open file in write-binary mode
with open('first-pickle.pkl', 'wb') as file:
    # Dump data with highest protocol for best performance
    pickle.dump(clf, file, protocol=pickle.HIGHEST_PROTOCOL)

In [55]:
# now try opening it

with open('first-pickle.pkl', 'rb') as file:
    test = pickle.load(file)

In [56]:
test

SVC()

In [57]:
test.score(X[0:1], y[0:1])          # -> 1.0 if correct, 0.0 if not

1.0

In [ ]:
# Yay it works!!!